### ISSUE TITLE
Fix timezone issue

### ISSUE THREAD

**Issue by cheeaun** [webuildsg/geekbrunch.sg#7]
![22496185_10155256268699582_5253355153374855043_o](https://user-images.githubusercontent.com/2296/31659349-6e8fd2e0-b366-11e7-9d5e-7cc4bf6977b8.jpg)

Timezone: GMT+11

**Comment by sebdeckers** [comment]
If you decide to do l10n it could make sense to show the local time, since it's a real-world event and visitors to SG might get confused on the day.

So:
1. Always show the SGT (SST) local time.
2. For useragents in other timezones, show their local time including timezone in addition to the local time.

**Comment by cheeaun** [comment]
Fixed in 9e4da59eae53cb8dd03892d15069371d55c06866 . Showing SGT-only time
